name: Go Build, Docker & MkDocs Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual execution

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for Linux
        run: |
          GOARCH=amd64 GOOS=linux go build -o 3270Connect go3270Connect.go

      - name: Test Go Project
        run: go test -v ./...

      - name: Run Linux Binary (Verbose & Headless)
        run: |
          chmod +x ./3270Connect
          ./3270Connect -runApp 1
          ./3270Connect -verbose -headless

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: 3270Connect-linux
          path: 3270Connect

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for Windows
        shell: pwsh
        run: |
          $env:GOARCH="amd64"
          $env:GOOS="windows"
          go build -o 3270Connect.exe go3270Connect.go

      - name: Test Go Project
        run: go test -v ./...

      - name: Run Windows Binary (Verbose & Headless)
        shell: pwsh
        run: |
          .\3270Connect.exe -runApp 1
          .\3270Connect.exe -verbose -headless

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: 3270Connect-windows
          path: 3270Connect.exe

  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GHCR push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4